# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-26 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import websqlrunner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('connstrings', models.TextField(validators=[websqlrunner.models.validate_connection_strings])),
                ('parallel', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('R', 'Running'), ('S', 'Success'), ('F', 'Fail')], default='R', max_length=50)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SqlScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('file', models.FileField(upload_to='scripts')),
                ('createdby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='run',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websqlrunner.SqlScript'),
        ),
        migrations.AddField(
            model_name='run',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
