# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-26 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websqlrunner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='parallel',
        ),
    ]
